# Matrix controller sample configuration

# How to connect to RabbitMQ
rabbitmq_host: localhost
rabbitmq_port: 5672
rabbitmq_username: user
rabbitmq_password: user
event_exchange: events

# Names of the nodes that the controller will run on.
# These need not be real hostnames.
sim_nodes:
    - node1

# The TCP port the controllers should listen to
# for incoming connections agent connections
controller_port:
    node1: 16001

# The number of agent processes
# that will run on each node
num_agentprocs:
    node1: 1

# The number of store processes
# that will run on each node
num_storeprocs:
    node1: 1

# The root seed
root_seed: 42

# Number of rounds to run the simulation for
num_rounds: 10
